### ISSUE TITLE
Syntesizer model not working with the repo

### ISSUE THREAD

**Issue by Dannypeja** [padmalcom/Real-Time-Voice-Cloning-German#15]
Hi, 
I've tried now to use your Model with the Toolbox an error with the synthesizer. The encoder does not produce issues. 
I am working on a Mac and the conrentin repo is working fine with the english models. 

Error: 
```
Synthesizer using device: cpu
Trainable Parameters: 30.870M
Traceback (most recent call last):
  File "/Users/dape/Real-Time-Voice-Cloning/toolbox/__init__.py", line 227, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds)
  File "/Users/dape/Real-Time-Voice-Cloning/synthesizer/inference.py", line 86, in synthesize_spectrograms
    self.load()
  File "/Users/dape/Real-Time-Voice-Cloning/synthesizer/inference.py", line 64, in load
    self._model.load(self.model_fpath)
  File "/Users/dape/Real-Time-Voice-Cloning/synthesizer/models/tacotron.py", line 497, in load
    self.load_state_dict(checkpoint["model_state"])
  File "/Users/dape/miniconda3/envs/rtvc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron:
	size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([73, 512]) from checkpoint, the shape in current model is torch.Size([66, 512]).
```

I appreciated your help!

**Comment by padmalcom** [comment]
Hi, I can't reproduce this error, which release of the models do you use?
Edit: I saw in your other issue that you were using 0.2 which is not compatible to the current main branch. Please use 0.3.

**Comment by Dannypeja** [comment]
Hi, I have figured it out. Totally my fault. I had tried to use it with the original repo without the modified symbols.py.
I believe I even understood the error in the last line.
```
RuntimeError: Error(s) in loading state_dict for Tacotron:
	size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([73, 512]) from checkpoint, the shape in current model is torch.Size([66, 512]).
```
The difference in tensor size is exactly the missing 7 symbols ("ÄÖÜßäöü")
