### ISSUE TITLE
Error while testing the synthesizer: Assign requires shapes of both tensors to match. lhs shape= [66,512] rhs shape= [73,512]

### ISSUE THREAD

**Issue by zwogorg** [padmalcom/Real-Time-Voice-Cloning-German#3]
Hi,

I'm trying to test Real-Time-Voice-Cloning with the German language model. I'm using commit [5425557](https://github.com/CorentinJ/Real-Time-Voice-Cloning/tree/5425557efe30863267f805851f918124191e0be0), which is the last one that uses the Tensorflow synthesizer before it changed to Pytorch.
It works fine, when I use the English language pretained model as [per the wiki](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models/2cd3887f379d4921b193214973b463043efa5c23). But when I try to use the German model I get the following error:

```
Testing the synthesizer... (loading the model will output a lot of text)
Constructing model: Tacotron
[bunch of warnings about depreceated functions that will be removed in Tensorflow 2]
initialisation done /gpu:0
Initialized Tacotron model. Dimensions (? = dynamic shape): 
  Train mode:               False
  Eval mode:                False
  GTA mode:                 False
  Synthesis mode:           True
  Input:                    (?, ?)
  device:                   0
  embedding:                (?, ?, 512)
  enc conv out:             (?, ?, 512)
  encoder out (cond):       (?, ?, 768)
  decoder out:              (?, ?, 80)
  residual out:             (?, ?, 512)
  projected residual out:   (?, ?, 80)
  mel out:                  (?, ?, 80)
  <stop_token> out:         (?, ?)
  Tacotron Parameters       28.439 Million.
Loading checkpoint: ger/bin/synthesizer/saved_models/logs-my_run/taco_pretrained/tacotron_model.ckpt-202000
2021-04-05 01:03:06.213104: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2493420000 Hz
2021-04-05 01:03:06.213472: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ea3baa3eb0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-05 01:03:06.213501: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-04-05 01:03:06.214993: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-04-05 01:03:06.435870: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-04-05 01:03:06.435981: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (g200): /proc/driver/nvidia/version does not exist
Traceback (most recent call last):
  File "/home/g/RTV/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/g/RTV/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/g/RTV/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [66,512] rhs shape= [73,512]
	 [[{{node save/Assign_40}}]]
```

I'm using Python 3.7, Tensorflow 1.15.5 and Torch 1.7.1 (Torch 1.8.x throws a segfault after "Preparing the encoder, the synthesizer and the vocoder...")

I'm new to Tensorflow, so maybe someone can help? It runs without problems when I use the German encoder and vocoder and the English synthesizer model, so I'm thinking this is a problem with the German model, not with Real-Time-Voice-Cloning.

**Comment by padmalcom** [comment]
Hi, the model I provide is trained for PyTorch, not for Tensorflow. I've read that models can be converted, but I do not have any experience here. You might consider switching to PyTorch.

**Comment by simteraplications** [comment]
I don't know if this is right here. But does this mean i can also use it with the newest version of rela time voice cloning? I am confused because the autho sais it does not but when this already uses the new synth it should. I am german my self so i am interested in this a lot.

**Comment by padmalcom** [comment]
Please use the current implementation and the models from release >=2 to test again. The old models from release 1 are no longer working.

**Comment by eqikkwkp25-cyber** [comment]
People will observe the shape mismatch issue when they overwrite the original symbols.py with the one from your repository, do not do that. 

New models work well here though i do not hear any relationship between my voice input and cloned output :-)

**Comment by padmalcom** [comment]
What @eqikkwkp25-cyber said is true, so adapt the symbols.py accordinly or use the new models (which I recommend anyway).
